### ISSUE TITLE
user_history_data is not available

### ISSUE THREAD

**Issue by Zegelink** [dojeon-ai/DraftRec#2]
Dear authors,

Could you fix the link for [user_history_data (~16gb)](https://drive.google.com/file/d/1km--Hmawldbi5mrw6dGeXzJQPttfXJTE/view?usp=sharing)? 
Thank you very much.

**Comment by joonleesky** [comment]
Sorry for the late replies. 
We've updated the link for user_history_data.

Thank you for your attention.
